// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyskyvwxbpnlveamxwlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5c2t5dnd4YnBubHZlYW14d2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTMyMTEsImV4cCI6MjA3Mjk2OTIxMX0.EzWNQvch4at0TVUGrj8-ae6VQtcUOpxXwMe3AAxj49A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});